### ISSUE TITLE
"Build and enable a custom subtheme" had no effect

### ISSUE THREAD

**Issue by pmackay** [drupalprojects/kalatheme#137] opened 2014-08-29 09:35 UTC
I installed Kalatheme 7.x-3.0 on Panopoly and tried to tick "Build and enable a custom subtheme" to create one, but when I saved it had no effect. I couldnt see any new subtheme generated. I could create one using drush though.

**Comment by enxox** [comment] 2014-09-02 08:49
Same for me. 
Last version of Kalatheme on custom Drupal, themes and libraries folder on 777 permission, update module enabled, stark as admin theme (as I have read on some other issues). 

Nothing seem to work.

Theme settings page says "Your webserver is correctly configured to allow for custom Bootstrap libraries and subtheme generation!" but when I try to save a subtheme, only "The configuration options have been saved." appears with no results.

I'm not still able to use drush.

**Comment by npoku** [comment] 2014-09-02 08:58
I also had the same issue even on local dev. Running default Drupal Districution + Panolopy modules + Kalatheme. 

Checking the box to create a subtheme didn't work for me, but drush did. 

Enxox, can you explain, "not being able to use drush". As in general or just to create a subtheme?

**Comment by enxox** [comment] 2014-09-02 08:59
It's my personal fault, I never installed it :)

**Comment by npoku** [comment] 2014-09-02 09:03
@enxox. Ahhhh. Highly recommended. It would make your life easier :-). 

Until I also get any solution to create a sub-theme via web interface Drush it going to be for me.

**Comment by Yanivshp** [comment] 2014-11-01 15:51
Had the same problem using Panopoly + Kalatheme.

The solution was to set the "Administration theme" to "Default theme" (it was previously set to "Seven").

**Comment by haringsrob** [comment] 2015-01-21 13:03
@Yanivshp your suggestion helped!

Perhaps we should add this to docs for now?

**Comment by vouko** [comment] 2015-07-14 20:26
Thanks @Yanivshp. I just lost the last couple hours on this. You saved the rest of my day. 

I highly suggest fixing this or adding to docs...

**Comment by soniktrooth** [comment] 2015-09-02 20:57
This is a duplicate of #119

**Closed as completed by soniktrooth** 2015-09-02 20:57 UTC
